# Generated by Django 5.0.2 on 2025-04-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', 'add_user_to_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert'), ('snack', 'Snack'), ('beverage', 'Beverage'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
