# Generated by Django 5.0.2 on 2025-04-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeimage_set', to='recipes.recipe'),
        ),
    ]
